[phases.setup]
nixPkgs = ["php84", "php84Extensions.pdo", "php84Extensions.pdo_mysql", "php84Extensions.mbstring", "php84Extensions.xml", "php84Extensions.curl", "php84Extensions.zip", "php84Extensions.tokenizer", "php84Extensions.fileinfo", "php84Extensions.ctype", "php84Extensions.openssl", "phpPackages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-reqs"]

[phases.build]
cmds = [
  "chmod -R 775 storage bootstrap/cache"
]

[start]
cmd = "php artisan config:clear && php artisan migrate --force --no-interaction; php artisan db:seed --class=ServiceSeeder --force --no-interaction; php artisan db:seed --class=AdminSeeder --force --no-interaction; php -S 0.0.0.0:${PORT:-3000} -t public"
